name: Events workflow
# on: [workflow_dispatch, push]
on:
  push:
    branches:
      - main
  pull_request:
    types: [labeled]
  
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Check Node Installation
        run: node -v
    

  
  second-job:
    runs-on: Ubuntu-latest
    needs: first-job
    steps:
      - name: Greeting-2
        run: echo "Welcome to CI and CD "
      - name: Thanks -2
        run: echo "Thank you learning devops "

 