name: My first workflow
on:
  push:
    branches:
      - main
jobs:
  first-job:
    runs-on: Ubuntu-latest
    steps:
      - name: Welcome greeting
        run: echo "Welcome to Github Actions! "
      - name: Thank you Message
        run: echo "Thank you for using Github Actions! "

 
