name: Expressions & Contexts Demo
on: [workflow_dispatch , push]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Github Expression step-1
        run: echo "${{ 'This is an expression'}}"
      - name: Github Context-1
        run: echo "${{ github }}"
      - name: Ouput Commands
        run: echo "${{ toJSON(github) }}"