name: If Key Demo
on: [workflow_dispatch , push]
run-name: Demo by @${{ github.actor }}

jobs:
  job-1:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Github Expression step-1
        run: echo "${{ 'This will run only if event is push'}}"     
  
  job-2:
    runs-on: ubuntu-latest
    steps:
    - name: Contexts
      run: |
          echo "${{ toJson(runner)}}"
          echo "${{ toJson(github)}}"
          echo "${{ toJson(job)}}"
        
  

