name: Status check
on: [workflow_dispatch, push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: sleep 20
      - name: Fail
        run: exit 1
      - name: Runs of Failure
        if: failure()
        run: echo "This will run only if the job fails"
      - name: Runs on Step Failure
        if: steps.Fail.conclusion == 'failure'
        run: echo "This will run only if the step fails"
      - name: Always Runs
        if: always()
        run: echo "This will always run"
      - name: Runs when cancelled
        if: cancelled()
        run: echo "This will run only if the job is cancelled"


  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - name: step-2
        run: echo "Job-2"